### ISSUE TITLE
ofxUnitTests.h not found when compiling project

### ISSUE THREAD

**Issue by alexanderwallin** [thomasgeissl/ofPackageManager#1]
First of all, this packager is a brilliant idea. Coming from the web dev universe, having everything in one openFrameworks folder does not feel like a good idea. So big up!

I ran into an issue setting this project up:
1. I cloned the repo into `path/to/openFrameworks/apps/ofPackageManager`
2. I ran `clone_dependencies.sh` after `cd`ing to its folder
3. I ran `make` in the project root

The problem is that the `ofxUnitTests` addon is neither copied to nor found. This is the error output i got in the terminal:

``` sh
/MY_PATH_TO/openFrameworks/of_v0.9.3_osx_release/apps/ofPackageManager/src/main.cpp:2:10: fatal error:
      'ofxUnitTests.h' file not found
#include "ofxUnitTests.h"
         ^
1 error generated.
make[1]: *** [obj/osx/Release/src/main.o] Error 1
make: *** [Release] Error 2
```

I am quite new to the C++ world, so please correct me if I'm doing anything wrong!

Cheers :)

**Comment by thomasgeissl** [comment]
Hey @alexanderwallin, 
thanks for giving it a try.
ofxUnitTests is an oF core addon. Not sure if oF v0.9.3 already includes it already. But you can grab a copy from the current master and paste it into addons/ofxUnitTests/src, it should not have any dependencies. 

I wont be able to test it this week, but let me know if it works. I will continue working on the package manager in the future. Also, please note that this is far from being production ready. But do not hesitate to let me know about issues and recommendations.

Thomas

**Comment by thomasgeissl** [comment]
Does your openframeworks/addons contain ofxUnitTests?
I don't know why it does not find the the addon. It should be included.

A quick workaround would be to compile the app without the coloured logger channel.
Just out-comment the include of ofxUnitTests.h and the first lines in the main where the channel is set. It should be also out-commented in addons.make.

Let me know if this helps.

**Comment by alexanderwallin** [comment]
Weirdly enough, ofxUnitTests is in the oF core but not included in the downloads bundle. I have manually added it to the oF addons folder.

Now I get this when running `make` in the project directory:

``` sh
makefileCommon/config.shared.mk:218: *** This package doesn't support your platform, probably you downloaded the wrong package?.  Stop.
make: *** [Release] Error 2
```

No idea if it's related to this package.

**Comment by thomasgeissl** [comment]
Did you set `OF_ROOT` in config.make?
You can also try copying the Makefile from openFrameworks/apps/myApps/emptyExample to ofPackageManager?

Generating a x-code project with the project generator could be an alternative, it should already support local addons.

**Comment by alexanderwallin** [comment]
Specifying an absolute path in `config.make` did make that error go away. I have declared a global `$OF_ROOT` in my `~/.bash_profile`. Maybe `config.make` could assign `OF_ROOT` only if no global variable is available?

The compilation now fails with:

``` sh
In file included from /PATH/TO/OF/apps/ofPackageManager/src/main.cpp:2:
/PATH/TO/OF/addons/ofxUnitTests/src/ofxUnitTests.h:263:17: error:
      no member named 'method' in 'ofHttpRequest'
            req.method = ofHttpRequest::POST;
            ~~~ ^
/PATH/TO/OF/addons/ofxUnitTests/src/ofxUnitTests.h:263:41: error:
      no member named 'POST' in 'ofHttpRequest'
            req.method = ofHttpRequest::POST;
                         ~~~~~~~~~~~~~~~^
/PATH/TO/OF/addons/ofxUnitTests/src/ofxUnitTests.h:265:17: error:
      no member named 'body' in 'ofHttpRequest'
            req.body =
            ~~~ ^
/PATH/TO/OF/addons/ofxUnitTests/src/ofxUnitTests.h:282:29: error:
      no member named 'body' in 'ofHttpRequest'
                cout << req.body << endl;
                        ~~~ ^
In file included from /PATH/TO/OF/apps/ofPackageManager/src/main.cpp:3:
/PATH/TO/OF/apps/ofPackageManager/src/ofApp.h:44:5: error:
      unknown type name 'ofJson'
    ofJson getPackageJson();
    ^
/PATH/TO/OF/apps/ofPackageManager/src/ofApp.h:45:5: error:
      unknown type name 'ofJson'
    ofJson getPackageManagerJson();
    ^
/PATH/TO/OF/apps/ofPackageManager/src/ofApp.h:46:5: error:
      unknown type name 'ofJson'
    ofJson getLocalConfigJson();
    ^
/PATH/TO/OF/apps/ofPackageManager/src/ofApp.h:47:5: error:
      unknown type name 'ofJson'
    ofJson getGlobalConfigJson();
    ^
/PATH/TO/OF/apps/ofPackageManager/src/ofApp.h:60:5: error:
      unknown type name 'ofJson'
    ofJson _configJson;
    ^
9 errors generated.
make[1]: *** [obj/osx/Release/src/main.o] Error 1
make: *** [Release] Error 2
```

**Comment by thomasgeissl** [comment]
Sounds like a compatibility issue. ofJson was probably added after 0.9.3 and ofHttpRequest was probably refactored. Also I am not sure if the makefile system works well with local addons. I was using qt creator, don't remember if I tried using make.
Good time for me to do some tests and update the readme. I'll let you know.

**Comment by alexanderwallin** [comment]
Cool! Just let me know if you want me to test anything out.

**Comment by thomasgeissl** [comment]
As written above it will not compile using 0.9.3 and I am not planning to add support for it. You will have to use the current master.
I could not compile it using the makefile system, did not spend much time on it. Both, importing the project in qt creator using the wizard and generating an x-code project worked for me.

I updated the readme.

**Comment by thomasgeissl** [comment]
I have updated the package manager and will continue working on it the next days/weeks. feel free to test and give feedback.
